import { Inter } from "next/font/google";
import Header from "./components/Header.jsx";
import Navbar from "./components/Navbar.jsx";
import "./globals.css";
import { Providers } from "./store/providers.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Commerce",
  description: "Generated by Aadesh Shinde",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />

          <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
